# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - run: composer self-update
      - restore_cache:
          keys:
          - composer-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - composer-

      - run: composer install

      - save_cache:
          paths:
            - ./vendor
          key: composer-{{ checksum "composer.json" }}

      - run: php --version && php -m

      # run tests!
      - run: vendor/bin/phpunit
